### ISSUE TITLE
feat: Add this to the AUR

### ISSUE THREAD

**Issue by sitolam** [shorebirdtech/install#36]
**Description**

Add shorebird to the AUR.

**Additional Context**

I wrote a little PKGBUILD already that works but I don't know how it really works or if it is even correct. I just know that it works.
```
# Maintainer: Your Name <your.email@example.com>
pkgname=shorebird-cli
pkgver=1.4.9
pkgrel=1
pkgdesc="Shorebird CLI for interacting with Shorebird services"
arch=('x86_64')
url="https://github.com/shorebirdtech/install"
license=('Apache' 'MIT')
depends=('bash' 'curl')
source=("install.sh::https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh")
sha256sums=('SKIP')

package() {
  install -Dm755 "$srcdir/install.sh" "$pkgdir/usr/bin/shorebird-install.sh"
  cd "$pkgdir/usr/bin"
  ./shorebird-install.sh --force
  rm shorebird-install.sh

}
```

**Comment by eseidel** [comment]
I presume you mean https://aur.archlinux.org/?

**Comment by sitolam** [comment]
> I presume you mean https://aur.archlinux.org/?

Yes

**Comment by eseidel** [comment]
I think this is best left for someone else to do.  None of our core team use archlinux.  Someone else is welcome to submit shorebird.

Thanks!
